// Geometry configuration constants.
// Centralizes magic numbers used throughout geometry step definitions.

export const GEOMETRY_CONFIG = {
  // Stroke widths
  STROKE_WIDTH_THIN: 0.5,
  STROKE_WIDTH_MEDIUM: 1.0,
  STROKE_WIDTH_THICK: 2.0,
  STROKE_WIDTH_OUTLINE: 2.0,

  // Point sizes
  POINT_RADIUS_SMALL: 1.0,
  POINT_RADIUS_MEDIUM: 2.0,
  POINT_RADIUS_LARGE: 3.0,

  // Line extension
  LINE_EXTENSION_MULTIPLIER: 2.2,

  // Tolerance
  DEFAULT_TOLERANCE: 0.001,

  // Coordinate system
  COORDINATE_SYSTEM_ARROW_LENGTH_RATIO: 1 / 24,

  // Golden ratio
  GOLDEN_RATIO: (1 + Math.sqrt(5)) / 2,

  // Position ratios
  C1_POSITION_RATIO: 5 / 8,
  C2_POSITION_RATIO: 3 / 8,
} as const;

// Re-export individual constants for backward compatibility
export const STROKE_WIDTH_THIN = GEOMETRY_CONFIG.STROKE_WIDTH_THIN;
export const STROKE_WIDTH_MEDIUM = GEOMETRY_CONFIG.STROKE_WIDTH_MEDIUM;
export const STROKE_WIDTH_THICK = GEOMETRY_CONFIG.STROKE_WIDTH_THICK;
export const STROKE_WIDTH_OUTLINE = GEOMETRY_CONFIG.STROKE_WIDTH_OUTLINE;
export const POINT_RADIUS_SMALL = GEOMETRY_CONFIG.POINT_RADIUS_SMALL;
export const POINT_RADIUS_MEDIUM = GEOMETRY_CONFIG.POINT_RADIUS_MEDIUM;
export const POINT_RADIUS_LARGE = GEOMETRY_CONFIG.POINT_RADIUS_LARGE;
export const LINE_EXTENSION_MULTIPLIER = GEOMETRY_CONFIG.LINE_EXTENSION_MULTIPLIER;
export const DEFAULT_TOLERANCE = GEOMETRY_CONFIG.DEFAULT_TOLERANCE;
export const COORDINATE_SYSTEM_ARROW_LENGTH_RATIO =
  GEOMETRY_CONFIG.COORDINATE_SYSTEM_ARROW_LENGTH_RATIO;
export const GOLDEN_RATIO = GEOMETRY_CONFIG.GOLDEN_RATIO;
export const C1_POSITION_RATIO = GEOMETRY_CONFIG.C1_POSITION_RATIO;
export const C2_POSITION_RATIO = GEOMETRY_CONFIG.C2_POSITION_RATIO;
